/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Development_Student_System_Development */

#ifndef _Included_Development_Student_System_Development
#define _Included_Development_Student_System_Development
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Development_Student_System_Development
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Development_1Student_1System_Development_clear
  (JNIEnv *, jobject);

/*
 * Class:     Development_Student_System_Development
 * Method:    time
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Development_1Student_1System_Development_time
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
